apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mozstage
resources:
  - ./namespace.yaml
  - ../hello/deployment.yaml
  - ../hello/ingress.yaml
  - ../hello/service.yaml
  - ../proxy/deployment.yaml
  - ../proxy/ingress.yaml
  - ../proxy/service.yaml
