apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watcher
rules:
  - apiGroups: [ "apps" ]
    resources: [ "deployments" ]
    verbs: [ "*" ]
  - apiGroups: [ "" ]
    resources: [ "pods" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "" ]
    resources: [ "pods/exec" ]
    verbs: [ "create" ]
