apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: watcher
subjects:
  - namespace: moz
    kind: ServiceAccount
    name: watcher
